# Generated by Django 5.0.6 on 2026-05-29 22:06

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomalie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_modified', models.BigIntegerField(default=0, editable=False, help_text='Timestamp epoch ms, mis a jour par trigger')),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(editable=False, help_text='Genere cote mobile', unique=True)),
                ('type_anomalie', models.CharField(max_length=100)),
                ('gravite', models.CharField(choices=[('FAIBLE', 'Faible'), ('MOYENNE', 'Moyenne'), ('ELEVEE', 'Elevee')], default='MOYENNE', max_length=20)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('EN_TRAITEMENT', 'En traitement'), ('RESOLUE', 'Resolue')], default='OUVERTE', max_length=20)),
                ('date_heure', models.DateTimeField()),
                ('localisation', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'anomalie',
            },
        ),
        migrations.CreateModel(
            name='Etape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_modified', models.BigIntegerField(default=0, editable=False, help_text='Timestamp epoch ms, mis a jour par trigger')),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ordre_prevu', models.PositiveIntegerField()),
                ('ordre_optimise', models.PositiveIntegerField(blank=True, null=True)),
                ('statut_visite', models.CharField(choices=[('A_VISITER', 'A visiter'), ('VISITEE', 'Visitee'), ('ECHEC', 'Echec')], default='A_VISITER', max_length=20)),
            ],
            options={
                'db_table': 'etape',
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_modified', models.BigIntegerField(default=0, editable=False, help_text='Timestamp epoch ms, mis a jour par trigger')),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero_x3', models.CharField(help_text='N de programme cote Sage X3', max_length=30, unique=True)),
                ('date_programme', models.DateField()),
                ('type_programme', models.CharField(choices=[('COLLECTE', 'Collecte'), ('RESTITUTION', 'Restitution')], max_length=20)),
                ('statut', models.CharField(choices=[('PLANIFIE', 'Planifie'), ('EN_COURS', 'En cours'), ('CLOTURE', 'Cloture')], default='PLANIFIE', max_length=20)),
                ('heure_debut', models.DateTimeField(blank=True, null=True)),
                ('heure_fin', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'programme',
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('capacite', models.PositiveIntegerField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'vehicule',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_x3', models.CharField(help_text='Code de correspondance Sage X3 (BPCUSTOMER)', max_length=30, unique=True)),
                ('raison_sociale', models.CharField(max_length=255)),
                ('type_client', models.CharField(choices=[('DEPOT', 'Depot'), ('REVENDEUR', 'Revendeur'), ('GROS_CLIENT', 'Gros client'), ('PARTICULIER', 'Particulier')], max_length=20)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'client',
                'indexes': [models.Index(fields=['code_x3'], name='client_code_x3_ea1d3c_idx'), models.Index(fields=['raison_sociale'], name='client_raison__586c75_idx')],
            },
        ),
        migrations.CreateModel(
            name='LigneProgramme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_modified', models.BigIntegerField(default=0, editable=False, help_text='Timestamp epoch ms, mis a jour par trigger')),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantite_prevue', models.PositiveIntegerField()),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_prevues', to='distribution.etape')),
            ],
            options={
                'db_table': 'ligne_programme',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_modified', models.BigIntegerField(default=0, editable=False, help_text='Timestamp epoch ms, mis a jour par trigger')),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(editable=False, help_text='Genere cote mobile', unique=True)),
                ('type_operation', models.CharField(choices=[('COLLECTE', 'Collecte'), ('RESTITUTION', 'Restitution'), ('LIVRAISON_DIRECTE', 'Livraison directe'), ('CONSIGNE', 'Consigne')], max_length=30)),
                ('sous_type', models.CharField(blank=True, choices=[('BCR', 'Bon de Commande Recharge'), ('BCT', 'Bon de Commande Transport')], max_length=10, null=True)),
                ('date_heure', models.DateTimeField()),
                ('localisation_saisie', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('mode_paiement', models.CharField(blank=True, choices=[('ESPECES', 'Especes'), ('MOBILE_MONEY', 'Mobile Money'), ('CHEQUE', 'Cheque'), ('VIREMENT', 'Virement'), ('CREDIT', 'Credit')], max_length=20, null=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_encaisse', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('est_encaissee', models.BooleanField(default=False)),
                ('signature_livreur', models.TextField(blank=True)),
                ('signature_client', models.TextField(blank=True)),
                ('nom_signataire_client', models.CharField(blank=True, max_length=255)),
                ('commentaire', models.TextField(blank=True)),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='distribution.etape')),
            ],
            options={
                'db_table': 'operation',
            },
        ),
        migrations.CreateModel(
            name='LigneOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_modified', models.BigIntegerField(default=0, editable=False, help_text='Timestamp epoch ms, mis a jour par trigger')),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(editable=False, help_text='Genere cote mobile', unique=True)),
                ('quantite_realisee', models.PositiveIntegerField(default=0)),
                ('quantite_collectee_vide', models.PositiveIntegerField(default=0)),
                ('quantite_consignee', models.PositiveIntegerField(default=0)),
                ('quantite_deconsignee', models.PositiveIntegerField(default=0)),
                ('montant_ligne', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='distribution.operation')),
            ],
            options={
                'db_table': 'ligne_operation',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_modified', models.BigIntegerField(default=0, editable=False, help_text='Timestamp epoch ms, mis a jour par trigger')),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(editable=False, help_text='Genere cote mobile', unique=True)),
                ('fichier', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('type_photo', models.CharField(choices=[('BORDEREAU', 'Bordereau signe'), ('LIVRAISON', 'Preuve de livraison'), ('ETAT_PLV', 'Etat du PLV'), ('ANOMALIE', 'Anomalie')], max_length=20)),
                ('localisation', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('date_heure', models.DateTimeField()),
                ('taille_octets', models.PositiveIntegerField(blank=True, null=True)),
                ('anomalie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='distribution.anomalie')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='distribution.operation')),
            ],
            options={
                'db_table': 'photo',
            },
        ),
        migrations.CreateModel(
            name='Plv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('adresse', models.TextField(blank=True)),
                ('localisation', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('SUSPENDU', 'Suspendu')], default='ACTIF', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plvs', to='distribution.client')),
            ],
            options={
                'db_table': 'plv',
            },
        ),
        migrations.AddField(
            model_name='etape',
            name='plv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etapes', to='distribution.plv'),
        ),
        migrations.AddField(
            model_name='anomalie',
            name='plv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies', to='distribution.plv'),
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_x3', models.CharField(max_length=30, unique=True)),
                ('libelle', models.CharField(max_length=255)),
                ('type_emballage', models.CharField(choices=[('B6', 'Bouteille 6 kg'), ('B12_5', 'Bouteille 12,5 kg'), ('B38', 'Bouteille 38 kg'), ('VRAC', 'Vrac')], max_length=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_consignation', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'produit',
                'indexes': [models.Index(fields=['code_x3'], name='produit_code_x3_2d66fe_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='produit',
            constraint=models.CheckConstraint(check=models.Q(('prix_unitaire__gte', 0)), name='produit_prix_positif'),
        ),
        migrations.AddConstraint(
            model_name='produit',
            constraint=models.CheckConstraint(check=models.Q(('montant_consignation__gte', 0)), name='produit_consignation_positive'),
        ),
        migrations.AddField(
            model_name='ligneprogramme',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='distribution.produit'),
        ),
        migrations.AddField(
            model_name='ligneoperation',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='distribution.produit'),
        ),
        migrations.AddField(
            model_name='programme',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programmes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='etape',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='distribution.programme'),
        ),
        migrations.AddField(
            model_name='anomalie',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='distribution.programme'),
        ),
        migrations.AddField(
            model_name='programme',
            name='vehicule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programmes', to='distribution.vehicule'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['etape'], name='operation_etape_i_93e4f0_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['date_heure'], name='operation_date_he_7161b1_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['last_modified'], name='operation_last_mo_6c06d8_idx'),
        ),
        migrations.AddConstraint(
            model_name='operation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('sous_type__isnull', False), ('type_operation', 'COLLECTE')), models.Q(models.Q(('type_operation', 'COLLECTE'), _negated=True), ('sous_type__isnull', True)), _connector='OR'), name='chk_operation_sous_type'),
        ),
        migrations.AddConstraint(
            model_name='operation',
            constraint=models.CheckConstraint(check=models.Q(('montant_total__gte', 0)), name='op_montant_total_positif'),
        ),
        migrations.AddConstraint(
            model_name='operation',
            constraint=models.CheckConstraint(check=models.Q(('montant_encaisse__gte', 0)), name='op_montant_encaisse_positif'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['last_modified'], name='photo_last_mo_dba8c4_idx'),
        ),
        migrations.AddConstraint(
            model_name='photo',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('operation__isnull', False), ('anomalie__isnull', True)), models.Q(('operation__isnull', True), ('anomalie__isnull', False)), _connector='OR'), name='chk_photo_exclusivite'),
        ),
        migrations.AddIndex(
            model_name='plv',
            index=models.Index(fields=['client'], name='plv_client__74b8bb_idx'),
        ),
        migrations.AddIndex(
            model_name='plv',
            index=models.Index(fields=['statut'], name='plv_statut_9a8683_idx'),
        ),
        migrations.AddConstraint(
            model_name='ligneprogramme',
            constraint=models.UniqueConstraint(fields=('etape', 'produit'), name='uq_ligne_programme_etape_produit'),
        ),
        migrations.AddIndex(
            model_name='ligneoperation',
            index=models.Index(fields=['last_modified'], name='ligne_opera_last_mo_ba77b4_idx'),
        ),
        migrations.AddConstraint(
            model_name='ligneoperation',
            constraint=models.UniqueConstraint(fields=('operation', 'produit'), name='uq_ligne_op_op_produit'),
        ),
        migrations.AddIndex(
            model_name='etape',
            index=models.Index(fields=['last_modified'], name='etape_last_mo_7db7a3_idx'),
        ),
        migrations.AddConstraint(
            model_name='etape',
            constraint=models.UniqueConstraint(fields=('programme', 'ordre_prevu'), name='uq_etape_programme_ordre'),
        ),
        migrations.AddIndex(
            model_name='anomalie',
            index=models.Index(fields=['programme'], name='anomalie_program_80e75e_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalie',
            index=models.Index(fields=['statut'], name='anomalie_statut_d1969a_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalie',
            index=models.Index(fields=['last_modified'], name='anomalie_last_mo_3acb47_idx'),
        ),
        migrations.AddIndex(
            model_name='programme',
            index=models.Index(fields=['utilisateur', 'date_programme'], name='programme_utilisa_22a3ee_idx'),
        ),
        migrations.AddIndex(
            model_name='programme',
            index=models.Index(fields=['last_modified'], name='programme_last_mo_b52859_idx'),
        ),
        migrations.AddConstraint(
            model_name='programme',
            constraint=models.UniqueConstraint(fields=('utilisateur', 'date_programme', 'type_programme'), name='uq_programme_livreur_jour'),
        ),
    ]
