# Generated by Django 5.0.6 on 2026-06-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_triggers_and_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='gps_horodatage',
            field=models.DateTimeField(blank=True, help_text="Horodatage de l'acquisition GPS au moment de l'enregistrement.", null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='gps_precision',
            field=models.FloatField(blank=True, help_text="Rayon d'incertitude de la position GPS en metres (valeur probante).", null=True),
        ),
    ]
