# Generated by Django 5.0.6 on 2026-06-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0005_remove_programme_uq_livreur_jour'),
    ]

    operations = [
        migrations.AddField(
            model_name='plv',
            name='code_plv',
            field=models.CharField(blank=True, help_text='Identifiant unique du PLV. Ex : PLVO101 (O=Ouaga), PLVB063 (B=Bobo)', max_length=20, null=True, unique=True),
        ),
    ]
