# Generated by Django 5.0.6 on 2026-06-06 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distribution', '0003_operation_gps_horodatage_operation_gps_precision'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentX3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_x3', models.CharField(max_length=40, unique=True)),
                ('type_document', models.CharField(choices=[('BCR', 'Bon de Collecte Recharge'), ('BL', 'Bordereau de Livraison')], max_length=10)),
                ('statut', models.CharField(default='SYNCHRONISE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bcr', models.ForeignKey(blank=True, help_text='BCR de reference (renseigne uniquement pour un BL).', limit_choices_to={'type_document': 'BCR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bls', to='mock_x3.documentx3')),
                ('operation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_x3', to='distribution.operation')),
            ],
            options={
                'verbose_name': 'Document X3',
                'verbose_name_plural': 'Documents X3',
                'db_table': 'mock_x3_document_x3',
                'indexes': [models.Index(fields=['type_document'], name='mock_x3_doc_type_do_6d38a9_idx'), models.Index(fields=['operation'], name='mock_x3_doc_operati_30bfc4_idx')],
            },
        ),
    ]
